package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Action_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("digitalWrite(");
    tgs.append(String.valueOf(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.actuator$8UoQ), PROPS.name$MnvL)));
    tgs.append(" ,");
    tgs.append(String.valueOf(SEnumOperations.getMemberName0(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.status$8Oxt))));
    tgs.append(");");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink actuator$8UoQ = MetaAdapterFactory.getReferenceLink(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b48bL, 0x1fafdb5fcad1b492L, "actuator");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty status$8Oxt = MetaAdapterFactory.getProperty(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b48bL, 0x1fafdb5fcad1b48eL, "status");
  }
}
