package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_STATUS extends EnumerationDescriptorBase {

  public EnumerationDescriptor_STATUS() {
    super(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b450L, "STATUS", "r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/2283284740571247696");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "high", 0x1fafdb5fcad1b451L, "r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/2283284740571247697");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "low", 0x1fafdb5fcad1b45aL, "r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/2283284740571247706");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b450L, 0x1fafdb5fcad1b451L, 0x1fafdb5fcad1b45aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_HIGH_0, myMember_LOW_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_HIGH_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HIGH":
        return myMember_HIGH_0;
      case "LOW":
        return myMember_LOW_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
