package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Actuator = 1;
  public static final int App = 2;
  public static final int Brick = 3;
  public static final int Sensor = 4;
  public static final int State = 5;
  public static final int Transition = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L);
    builder.put(0x1fafdb5fcad1b48bL, Action);
    builder.put(0x356a9ff97b4e3934L, Actuator);
    builder.put(0x356a9ff97b4e3937L, App);
    builder.put(0x356a9ff97b4de414L, Brick);
    builder.put(0x356a9ff97b4e3935L, Sensor);
    builder.put(0x1fafdb5fcad15f33L, State);
    builder.put(0x1fafdb5fcad1b47cL, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
