package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptApp = createDescriptorForApp();
  /*package*/ final ConceptDescriptor myConceptBrick = createDescriptorForBrick();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptState = createDescriptorForState();
  /*package*/ final ConceptDescriptor myConceptTransition = createDescriptorForTransition();
  /*package*/ final EnumerationDescriptor myEnumerationSTATUS = new EnumerationDescriptor_STATUS();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptApp, myConceptBrick, myConceptSensor, myConceptState, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.App:
        return myConceptApp;
      case LanguageConceptSwitch.Brick:
        return myConceptBrick;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.State:
        return myConceptState;
      case LanguageConceptSwitch.Transition:
        return myConceptTransition;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationSTATUS);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Action", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b48bL);
    b.class_(false, false, false);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/2283284740571247755");
    b.version(3);
    b.property("status", 0x1fafdb5fcad1b48eL).type(MetaIdFactory.dataTypeId(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b450L)).origin("2283284740571247758").done();
    b.associate("actuator", 0x1fafdb5fcad1b492L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4e3934L).optional(false).origin("2283284740571247762").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Actuator", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4e3934L);
    b.class_(false, false, false);
    // extends: ArduinoML.structure.Brick
    b.super_(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4de414L);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/3849064725405907252");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForApp() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "App", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4e3937L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/3849064725405907255");
    b.version(3);
    b.associate("init_state", 0x1fafdb5fcad1b4a6L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad15f33L).optional(false).origin("2283284740571247782").done();
    b.aggregate("brick", 0x356a9ff97b4e393aL).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4de414L).optional(false).ordered(true).multiple(true).origin("3849064725405907258").done();
    b.aggregate("state", 0x1fafdb5fcad1b4a0L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad15f33L).optional(false).ordered(true).multiple(true).origin("2283284740571247776").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Brick", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4de414L);
    b.class_(false, true, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/3849064725405885460");
    b.version(3);
    b.property("pin", 0x356a9ff97b4e3931L).type(PrimitiveTypeId.INTEGER).origin("3849064725405907249").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Sensor", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4e3935L);
    b.class_(false, false, false);
    // extends: ArduinoML.structure.Brick
    b.super_(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4de414L);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/3849064725405907253");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForState() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "State", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad15f33L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/2283284740571225907");
    b.version(3);
    b.aggregate("actions", 0x1fafdb5fcad1b496L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b48bL).optional(true).ordered(true).multiple(true).origin("2283284740571247766").done();
    b.aggregate("transition", 0x1fafdb5fcad1b499L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b47cL).optional(false).ordered(true).multiple(true).origin("2283284740571247769").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransition() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ArduinoML", "Transition", 0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b47cL);
    b.class_(false, false, false);
    b.origin("r:c3f7684f-829d-4d32-b054-5894ce11edee(ArduinoML.structure)/2283284740571247740");
    b.version(3);
    b.property("status", 0x1fafdb5fcad1b47eL).type(MetaIdFactory.dataTypeId(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad1b450L)).origin("2283284740571247742").done();
    b.associate("sensor", 0x1fafdb5fcad1b481L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4e3935L).optional(false).origin("2283284740571247745").done();
    b.associate("target", 0x1fafdb5fcad1b484L).target(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x1fafdb5fcad15f33L).optional(false).origin("2283284740571247748").done();
    return b.create();
  }
}
