package ArduinoML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Brick_Constraints extends BaseConstraintsDescriptor {
  public Brick_Constraints() {
    super(CONCEPTS.Brick$60);
  }

  public static class Pin_Property extends BasePropertyConstraintsDescriptor {
    public Pin_Property(ConstraintsDescriptor container) {
      super(PROPS.pin$IZRo, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:e2f1183a-0fd9-4d3d-a225-791f2fcbcf44(ArduinoML.constraints)", "6281736288926603216"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 1 && propertyValue <= 13;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.pin$IZRo, new Pin_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Brick$60 = MetaAdapterFactory.getConcept(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4de414L, "ArduinoML.structure.Brick");
  }

  private static final class PROPS {
    /*package*/ static final SProperty pin$IZRo = MetaAdapterFactory.getProperty(0x87da0c0a7e99440eL, 0xa46728249a7a2c96L, 0x356a9ff97b4de414L, 0x356a9ff97b4e3931L, "pin");
  }
}
